//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GiftShop.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int ID { get; set; }
        public string name { get; set; }
        public string description { get; set; }
        public string category { get; set; }
        public int quantity { get; set; }
        public byte[] image { get; set; }
        public decimal price { get; set; }
    }
}
